name: Run CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: [3.11, 3.12]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run pytest
      run: |
        pytest
